const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Behaviors.Flash,
		C3.Plugins.HTMLElement,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.HTMLElement.Acts.SetContent,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Dizi_Ana: 0},
	{Dizi_FisherYates: 0},
	{Dizi_Gecici: 0},
	{Touch: 0},
	{Ses: 0},
	{Tarayıcı: 0},
	{girisarkpln: 0},
	{bilgiarkpln: 0},
	{Btn_Genel: 0},
	{Fare: 0},
	{oyunarkpln: 0},
	{deger: 0},
	{Parlama: 0},
	{Kare: 0},
	{HTMLElementi: 0},
	{Spr_Tus: 0},
	{puan: 0},
	{Yazı: 0},
	{Yazı2: 0},
	{Dizi_Kontrol: 0},
	{Spr_Donut: 0},
	{Yazı_DonutSure: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{n: 0},
	{sec1: 0},
	{sec2: 0},
	{tipRenk: 0},
	{sayi: 0},
	{sure: 0},
	{tip: 0},
	{dogru_sayisi: 0},
	{ses: 0},
	{j: 0},
	{gecici: 0},
	{i: 0}
];

self.InstanceType = {
	Dizi_Ana: class extends self.IArrayInstance {},
	Dizi_FisherYates: class extends self.IArrayInstance {},
	Dizi_Gecici: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	Ses: class extends self.IInstance {},
	Tarayıcı: class extends self.IInstance {},
	girisarkpln: class extends self.ISpriteInstance {},
	bilgiarkpln: class extends self.ISpriteInstance {},
	Btn_Genel: class extends self.ISpriteInstance {},
	Fare: class extends self.IInstance {},
	oyunarkpln: class extends self.ISpriteInstance {},
	Kare: class extends self.ISpriteInstance {},
	HTMLElementi: class extends self.IHTMLElementInstance {},
	Spr_Tus: class extends self.ISpriteInstance {},
	puan: class extends self.ISpriteInstance {},
	Yazı: class extends self.ITextInstance {},
	Yazı2: class extends self.ITextInstance {},
	Dizi_Kontrol: class extends self.IArrayInstance {},
	Spr_Donut: class extends self.ISpriteInstance {},
	Yazı_DonutSure: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {}
}